### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by Nels-J** [MyLittleBoulangerie/boutiquelaravel#10]
- [x] Faire la [migration ]de la table, si la table n’existe pas
- [x] Faire le [model], si le model n’existe pas
- [x] Faire les [relations ]entre les models
- [x] Faire les [seeders] , si n’existe pas
- [x] Faire le [controller] si le controller n’existe pas
- [x] Faire la méthode dans le controller
- [x] Faire la [route]
- [x] Faire la [view]
- [x] Faire la [validation de formulaire]  si nécessaire
- [x] Coder la logique dans la méthode du controller

**Comment by vbruchon** [comment]
Issue complete
